'use strict';
const S=window.SAE,N=S.n,Dd=S.dict,C={},U=S.num.usuarios,LA=S.num.latitud,LO=S.num.longitud,$=s=>document.querySelector(s);
const rev={};[...S.A].forEach((ch,k)=>rev[ch]=k);
for(const c in S.str){const s=S.str[c],a=new Uint8Array(N);for(let i=0;i<N;i++)a[i]=rev[s[i]];C[c]=a}
for(const c in S.int)C[c]=Uint32Array.from(S.int[c]);
const v=(c,i)=>Dd[c][C[c][i]],fmt=n=>Math.round(n).toLocaleString('es-PE'),f1=n=>n.toLocaleString('es-PE',{maximumFractionDigits:1,minimumFractionDigits:1}),pc=(a,b)=>b?f1(100*a/b)+'%':'—',lb=s=>s||'Sin dato';
const FIL=[['periodo_sae','Periodo'],['grupo_sae_educunas','Grupo SAE / Educunas'],['unidad_territorial','Unidad territorial'],['departamento','Departamento'],['nivel','Nivel'],['modalidad','Modalidad'],['area','Área'],['rango_usuarios','Rango de usuarios']];
const sel={};FIL.forEach(([c])=>sel[c]=-1);sel.periodo_sae=Dd.periodo_sae.indexOf('2027');
const TT={res:'Resumen ejecutivo',ut:'Unidades territoriales',mod:'Modalidad y forma de atención',inf:'Infraestructura (Ficha 2025)',his:'Comparación histórica 2026–2027',grp:'Grupos de servicios educativos',fic:'Fichas por institución educativa'};
let tab='res',R=[],cache={k:'',v:null},MAT='co';
const hasF=i=>v('iieeconfichadeinfra2no25',i)==='Si';
function ix(skipPer){const k=JSON.stringify(sel)+skipPer;if(cache.k===k)return cache.v;const a=[],act=FIL.filter(([c])=>sel[c]>=0&&!(skipPer&&c==='periodo_sae')).map(([c])=>[C[c],sel[c]]);
 for(let i=0;i<N;i++){let ok=1;for(const[x,s]of act)if(x[i]!==s){ok=0;break}if(ok)a.push(i)}cache={k,v:a};return a}
function cnt(ix,c,asc){const n=Dd[c].length,a=new Float64Array(n),u=new Float64Array(n),x=C[c];for(const i of ix){a[x[i]]++;u[x[i]]+=U[i]}
 const r=Dd[c].map((l,k)=>[lb(l),a[k],u[k]]).filter(r=>r[1]);return asc?r.sort((p,q)=>p[0]<q[0]?-1:1):r.sort((p,q)=>q[1]-p[1])}
const dat=(t,h,r)=>R.push({t,h,r});
function bars(t,rows,tot,lim){rows=lim?rows.slice(0,lim):rows;const mx=Math.max(...rows.map(r=>r[1]),1);dat(t,['Categoría','SSEE','%','Usuarios'],rows.map(r=>[r[0],r[1],pc(r[1],tot),r[2]??'']));
 return`<div class=card><h3>${t}</h3>${rows.map(r=>`<div class=b><span>${r[0]}</span><div><i style="width:${100*r[1]/mx}%"></i></div><b>${fmt(r[1])} · ${pc(r[1],tot)}</b></div>`).join('')}</div>`}
function stack(t,labs,cols,cs){const tot=cs.reduce((a,b)=>a+b,0);dat(t,['Categoría','IE','%'],labs.map((l,k)=>[l,cs[k],pc(cs[k],tot)]));
 return`<div class=card><h3>${t}<small>Información 2025</small></h3><div class=stk>${cs.map((c,k)=>`<i style="width:${100*c/(tot||1)}%;background:${cols[k]}"></i>`).join('')}</div><div class=lg>${labs.map((l,k)=>`<span><em style="background:${cols[k]}"></em>${l}: <b>${fmt(cs[k])}</b> (${pc(cs[k],tot)})</span>`).join('')}</div></div>`}
function tbl(t,h,rows,keys,lim=400){dat(t,h,rows);return`<div class=card><h3>${t}<small>${rows.length>lim?`mostrando ${lim} de ${fmt(rows.length)} · el reporte incluye todo`:''}</small></h3><div class=tw><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,lim).map((r,j)=>`<tr ${keys?`data-k="${keys[j]}"`:''}>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
const kpis=a=>{dat('Indicadores clave',['Indicador','Valor','Detalle'],a.map(k=>[k[0],k[1],k[2]]));return`<div class=kpis>${a.map(k=>`<div class=kpi><small>${k[0]}</small><strong>${k[1]}</strong><span>${k[2]}</span></div>`).join('')}</div>`};
const KIT=['Brecha: no recibió / no posee','Brecha: kit en mal estado','Sin brecha: óptimo o aceptable'],KC=['#e11d48','#f59e0b','#059669'],AMB=['No tiene ambiente','Ambiente exclusivo','Ambiente compartido'],AC=['#e11d48','#059669','#2563eb'];
const code3=(ix,c)=>{const a=[0,0,0];for(const i of ix){const x=v(c,i);if(x==='0'||x==='1'||x==='2')a[+x]++}return a};
const opt=i=>['Si','1'].includes(v('cocina_optima',i));
/* ---------- pestañas ---------- */
const T={};
T.res=ix=>{const n=ix.length,u=ix.reduce((a,i)=>a+U[i],0),fi=ix.filter(hasF),m=code3(fi,'kitmenaje'),rur=ix.filter(i=>v('area',i)==='Rural').length;
 return kpis([['Servicios (SSEE)',fmt(n),'Servicios educativos atendidos'],['Usuarios',fmt(u),'Prom. '+f1(u/(n||1))+' por SSEE'],['Con ficha de infraestructura 2025',pc(fi.length,n),fmt(fi.length)+' de '+fmt(n)+' IE'],['Brecha en kit de menaje',pc(m[0]+m[1],fi.length),'Sobre IE con ficha 2025'],['Cocina en condición óptima',pc(fi.filter(opt).length,fi.length),'Sobre IE con ficha 2025'],['Ámbito rural',pc(rur,n),fmt(rur)+' SSEE']])
 +`<div class=grid2>`+bars('Por modalidad',cnt(ix,'modalidad'),n)+bars('Por nivel educativo',cnt(ix,'nivel'),n)+bars('Por rango de usuarios',cnt(ix,'rango_usuarios',1),n)+bars('Por unidad territorial (Top 12)',cnt(ix,'unidad_territorial'),n,12)+`</div>`};
T.ut=ix=>{const c='unidad_territorial',k=Dd[c].length,z=()=>new Float64Array(k),A={n:z(),u:z(),r:z(),f:z(),m:z(),c:z(),b:z(),o:z()};
 for(const i of ix){const g=C[c][i];A.n[g]++;A.u[g]+=U[i];if(v('area',i)==='Rural')A.r[g]++;if(hasF(i)){A.f[g]++;if(v('kitmenaje',i)!=='2')A.m[g]++;if(v('kitcocina',i)!=='2')A.c[g]++;if(v('kitmobiliario',i)!=='2')A.b[g]++;if(opt(i))A.o[g]++}}
 const o=[...Dd[c].keys()].filter(g=>A.n[g]).sort((a,b)=>A.u[b]-A.u[a]);
 const rows=o.map(g=>[Dd[c][g],fmt(A.n[g]),fmt(A.u[g]),pc(A.r[g],A.n[g]),pc(A.f[g],A.n[g]),pc(A.m[g],A.f[g]),pc(A.c[g],A.f[g]),pc(A.b[g],A.f[g]),pc(A.o[g],A.f[g])]);
 return`<div class=note>Clic en una fila para filtrar toda la página por esa unidad territorial. Brechas e indicadores de cocina calculados sobre IE con ficha 2025.</div>`+tbl('Resumen por unidad territorial',['Unidad territorial','SSEE','Usuarios','% rural','% con ficha 2025','% brecha menaje','% brecha cocina','% brecha mobiliario','% cocina óptima'],rows,o.map(g=>'ut:'+g))};
T.mod=ix=>{const n=ix.length;return`<div class=grid2>`+bars('Modalidad',cnt(ix,'modalidad'),n)+bars('Forma de atención',cnt(ix,'forma_atencion'),n)+bars('Tipo de ración',cnt(ix,'tipo_racion'),n)+bars('Región alimentaria',cnt(ix,'region_alimentaria'),n)+bars('Quintil de pobreza',cnt(ix,'quintil',1),n)+bars('Grupo SAE / Educunas',cnt(ix,'grupo_sae_educunas'),n)+`</div>`};
const MC={piso:{al:'material_predominante_piso_almac',co:'material_predominante_piso_cocin',cm:'material_predominante_piso_comed'},pared:{al:'material_predominante_paredes_al',co:'material_predominante_paredes_co',cm:'material_predominante_pared_com'},techo:{al:'material_predominante_techo_alma',co:'material_predominante_techo_coci',cm:'material_predominante_techo_come'}};
T.inf=ix=>{const fi=ix.filter(hasF),n=ix.length,sn=n-fi.length;let h=`<div class=note>🗓 <b>Información de la Ficha de Infraestructura 2025.</b> ${fmt(fi.length)} de ${fmt(n)} SSEE (${pc(fi.length,n)}) cuentan con ficha; ${fmt(sn)} no tienen ficha 2025 y por eso no registran datos de estado de infraestructura.</div>`;
 h+=`<div class=grid2>`+stack('Kit de menaje',KIT,KC,code3(fi,'kitmenaje'))+stack('Kit de cocina',KIT,KC,code3(fi,'kitcocina'))+stack('Kit de mobiliario',KIT,KC,code3(fi,'kitmobiliario'))+`</div><div class=grid2>`+stack('Ambiente de cocina',AMB,AC,code3(fi,'ambientecocina'))+stack('Ambiente de almacén',AMB,AC,code3(fi,'ambientealmacen'))+stack('Ambiente de comedor',AMB,AC,code3(fi,'ambientecomedor'))+`</div>`;
 const fN=fi.length;h+=`<div class=grid2>`+bars('Ficha de infraestructura 2025',cnt(ix,'iieeconfichadeinfra2no25'),n)+bars('Abastecimiento de agua · 2025',cnt(fi,'abastecimiento_agua_por'),fN)+bars('Servicio higiénico conectado a · 2025',cnt(fi,'servicio_higienico_conectado_a'),fN)+bars('Alumbrado proviene de · 2025',cnt(fi,'alumbrado_proviene_de'),fN)+`</div>`;
 h+=`<div class=card><h3>Material predominante · 2025</h3><div class=seg>${[['co','Cocina'],['al','Almacén'],['cm','Comedor']].map(([k,l])=>`<button data-mat=${k} class="${MAT===k?'on':''}">${l}</button>`).join('')}</div><div class=grid2>`+['piso','pared','techo'].map(m=>bars('Material del '+m,cnt(fi,MC[m][MAT]),fN).replace('class=card','class=nocard')).join('')+`</div></div>`;return h};
T.his=()=>{const ps=Dd.periodo_sae,ixa=ix(1),c='unidad_territorial',m=ps.map(()=>new Map()),tot=ps.map(()=>[0,0]),keys=ps.map(()=>new Set());
 for(const i of ixa){const p=C.periodo_sae[i],g=C[c][i];let o=m[p].get(g);if(!o)m[p].set(g,o=[0,0]);o[0]++;o[1]+=U[i];tot[p][0]++;tot[p][1]+=U[i];keys[p].add(C.cod_modular[i]*128+C.anexo[i])}
 const gs=[...new Set(m.flatMap(x=>[...x.keys()]))].sort((a,b)=>(m[2].get(b)||[0,0])[1]-(m[2].get(a)||[0,0])[1]),L=ps.length-1,d=(a,b)=>(a-b>0?'+':'')+fmt(a-b);
 const gl=(p,g)=>(m[p].get(g)||[0,0]);
 const rows=gs.map(g=>[Dd[c][g],...ps.map((_,p)=>fmt(gl(p,g)[0])),d(gl(L,g)[0],gl(L-1,g)[0]),...ps.map((_,p)=>fmt(gl(p,g)[1])),d(gl(L,g)[1],gl(L-1,g)[1])]);
 rows.push(['TOTAL',...tot.map(t=>fmt(t[0])),d(tot[L][0],tot[L-1][0]),...tot.map(t=>fmt(t[1])),d(tot[L][1],tot[L-1][1])]);
 let nw=0,sa=0,co=0;keys[L].forEach(k=>keys[L-1].has(k)?co++:nw++);keys[L-1].forEach(k=>keys[L].has(k)||sa++);
 return`<div class=note>Esta vista ignora el filtro de periodo y compara los tres periodos con los demás filtros aplicados.</div>`+kpis([...ps.map((p,k)=>['SSEE '+p,fmt(tot[k][0]),fmt(tot[k][1])+' usuarios']),['Nuevos en '+ps[L],fmt(nw),'No estaban en '+ps[L-1]],['Salen en '+ps[L],fmt(sa),'Estaban en '+ps[L-1]],['Continúan',fmt(co),'En ambos periodos']])
 +tbl('Evolución por unidad territorial',['Unidad territorial',...ps.map(p=>'SSEE '+p),'Δ SSEE',...ps.map(p=>'Usuarios '+p),'Δ Usuarios'],rows)};
/* ---------- geometría ---------- */
function geo(pts,type){if(!pts.length)return{poly:[],a:0,p:0};const la0=pts.reduce((a,p)=>a+p[0],0)/pts.length,lo0=pts.reduce((a,p)=>a+p[1],0)/pts.length,kx=111.32*Math.cos(la0*Math.PI/180),ky=110.574;
 const xy=pts.map(p=>[(p[1]-lo0)*kx,(p[0]-la0)*ky]),back=q=>[q[1]/ky+la0,q[0]/kx+lo0],cr=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]);
 const s=[...new Map(xy.map(p=>[p[0]+','+p[1],p])).values()].sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let h=s;
 if(s.length>2){const lo=[],up=[];for(const p of s){while(lo.length>1&&cr(lo[lo.length-2],lo[lo.length-1],p)<=0)lo.pop();lo.push(p)}for(const p of[...s].reverse()){while(up.length>1&&cr(up[up.length-2],up[up.length-1],p)<=0)up.pop();up.push(p)}h=lo.slice(0,-1).concat(up.slice(0,-1))}
 const ar=P=>Math.abs(P.reduce((a,p,k)=>{const q=P[(k+1)%P.length];return a+p[0]*q[1]-q[0]*p[1]},0))/2,pe=P=>P.reduce((a,p,k)=>{const q=P[(k+1)%P.length];return a+Math.hypot(p[0]-q[0],p[1]-q[1])},0);let P=h;
 const bb=(Q,t=0)=>{let x0=1e9,x1=-1e9,y0=1e9,y1=-1e9;for(const q of Q){x0=Math.min(x0,q[0]);x1=Math.max(x1,q[0]);y0=Math.min(y0,q[1]);y1=Math.max(y1,q[1])}return[x0,y0,x1,y1]};
 if(type==='env'){const[a,b,c,d]=bb(h);P=[[a,b],[c,b],[c,d],[a,d]]}
 else if(type==='rect'&&h.length>2){let best=1e18;for(let k=0;k<h.length;k++){const p=h[k],q=h[(k+1)%h.length],t=Math.atan2(q[1]-p[1],q[0]-p[0]),co=Math.cos(t),si=Math.sin(t),R=h.map(z=>[z[0]*co+z[1]*si,-z[0]*si+z[1]*co]),[a,b,c,d]=bb(R),A=(c-a)*(d-b);if(A<best){best=A;P=[[a,b],[c,b],[c,d],[a,d]].map(z=>[z[0]*co-z[1]*si,z[0]*si+z[1]*co])}}}
 else if(type==='circ'){let c=h[0].slice(),r=0;for(let k=1;k<200;k++){let f=h[0],md=0;for(const z of h){const dd=Math.hypot(z[0]-c[0],z[1]-c[1]);if(dd>md){md=dd;f=z}}c=[c[0]+(f[0]-c[0])/(k+1),c[1]+(f[1]-c[1])/(k+1)]}for(const z of h)r=Math.max(r,Math.hypot(z[0]-c[0],z[1]-c[1]));P=Array.from({length:72},(_,k)=>[c[0]+r*Math.cos(k*Math.PI/36),c[1]+r*Math.sin(k*Math.PI/36)])}
 return{poly:P.map(back),a:P.length>2?ar(P):0,p:P.length>1?pe(P):0}}
const G={by:'item',geo:'hull',sel:null,list:[],ixs:[]};let map,lay;
const GB={item:'Item (único por UT)',comite:'Comité de gestión',distrito:'Distrito',all:'Todos juntos'},GG={hull:'Envolvente convexa (Convex hull)',env:'Envolvente rectangular (Envelope)',rect:'Rectángulo de menor área',circ:'Círculo mínimo (Circle)'};
T.grp=ix=>{const m=new Map();for(const i of ix){const k=G.by==='all'?0:G.by==='distrito'?C.distrito[i]+'|'+C.provincia[i]+'|'+C.departamento[i]:C[G.by][i];let o=m.get(k);if(!o)m.set(k,o={i0:i,n:0,u:0,pts:[]});o.n++;o.u+=U[i];if(LA[i]<-0.5&&LA[i]>-19&&LO[i]<-68&&LO[i]>-82)o.pts.push([LA[i],LO[i]])}
 G.list=[...m.entries()].map(([k,o])=>{const g=geo(o.pts,G.geo),i=o.i0;return{k,o,g,label:G.by==='all'?'Todos los SSEE filtrados':G.by==='distrito'?v('distrito',i)+' · '+v('provincia',i):v(G.by,i)+' · '+v('unidad_territorial',i)}}).sort((a,b)=>b.o.u-a.o.u);
 if(!G.sel||!G.list.find(x=>x.k==G.sel))G.sel=G.list[0]?.k;
 const rows=G.list.map(x=>[x.label,fmt(x.o.n),fmt(x.o.u),f1(x.g.a),f1(x.g.p)]);
 return`<div class=card><h3>Mapa de servicios educativos · Minimum Bounding Geometry</h3><div class=ctl><label>Agrupar por<select id=gby>${Object.entries(GB).map(([k,l])=>`<option value=${k} ${G.by===k?'selected':''}>${l}</option>`).join('')}</select></label><label>Geometría envolvente<select id=ggeo>${Object.entries(GG).map(([k,l])=>`<option value=${k} ${G.geo===k?'selected':''}>${l}</option>`).join('')}</select></label></div><div id=gsel></div><div id=map></div></div>`
 +tbl('Grupo · SSEE · Usuarios · Área (km²) · Perímetro (km)',['Grupo','SSEE','Usuarios','Área (km²)','Perímetro (km)'],rows,G.list.map(x=>'g:'+x.k))};
function drawMap(){const x=G.list.find(z=>z.k==G.sel);if(!x)return;$('#gsel').innerHTML=`<div class=kpis style="margin-bottom:12px"><div class=kpi><small>Grupo</small><strong style="font-size:1.05rem">${x.label}</strong></div><div class=kpi><small>SSEE</small><strong>${fmt(x.o.n)}</strong></div><div class=kpi><small>Usuarios</small><strong>${fmt(x.o.u)}</strong></div><div class=kpi><small>Área (km²)</small><strong>${f1(x.g.a)}</strong></div><div class=kpi><small>Perímetro (km)</small><strong>${f1(x.g.p)}</strong></div></div>`;
 document.querySelectorAll('tr[data-k]').forEach(r=>r.classList.toggle('sel',r.dataset.k==='g:'+G.sel));
 if(!window.L)return setTimeout(drawMap,300);if(!map){map=L.map('map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);lay=L.layerGroup().addTo(map)}
 lay.clearLayers();const pts=[];for(const i of ix(0))if(sameGrp(i,x.k)&&LA[i]<-0.5)pts.push(i);pts.slice(0,5000).forEach(i=>L.circleMarker([LA[i],LO[i]],{radius:4,color:hasF(i)?'#059669':'#e11d48',weight:1,fillOpacity:.7}).bindTooltip(v('nombre_ie',i)+' · '+U[i]+' usuarios').addTo(lay));
 if(x.g.poly.length>2){const p=L.polygon(x.g.poly,{color:'#1d4ed8',weight:2,fillOpacity:.08}).addTo(lay);map.fitBounds(p.getBounds(),{padding:[20,20]})}else if(pts.length)map.setView([LA[pts[0]],LO[pts[0]]],12);setTimeout(()=>map.invalidateSize(),50)}
const sameGrp=(i,k)=>(G.by==='all'?0:G.by==='distrito'?C.distrito[i]+'|'+C.provincia[i]+'|'+C.departamento[i]:C[G.by][i])==k;
/* ---------- fichas ---------- */
let QS='';T.fic=()=>`<div class=card><h3>Fichas por institución educativa</h3><input id=q placeholder="Buscar por nombre, código modular o código local…" value="${QS}" autocomplete=off><div id=fres style="margin-top:12px"></div></div>`;
function fres(){const q=QS.trim().toLowerCase(),a=[];for(const i of ix(0)){if(!q||v('nombre_ie',i).toLowerCase().includes(q)||v('cod_modular',i).includes(q)||v('cod_local',i).includes(q)){a.push(i);if(a.length>=60)break}}
 $('#fres').innerHTML=`<div class=tw><table><thead><tr><th>Cód. modular</th><th>Institución</th><th>Nivel</th><th>Distrito</th><th>Usuarios</th><th>Ficha 2025</th></tr></thead><tbody>${a.map(i=>`<tr data-f=${i}><td>${v('cod_modular',i)}</td><td>${v('nombre_ie',i)}</td><td>${v('nivel',i)}</td><td>${v('distrito',i)}</td><td>${U[i]}</td><td>${hasF(i)?'<span class="pill ok">Sí</span>':'<span class="pill no">No</span>'}</td></tr>`).join('')}</tbody></table></div><p class=meta>${a.length>=60?'Primeros 60 resultados. Afine la búsqueda.':fmt(a.length)+' resultado(s)'}</p>`}
let byIE;function ficha(i){if(!byIE){byIE=new Map();for(let j=0;j<N;j++){const k=C.cod_modular[j]*128+C.anexo[j];(byIE.get(k)||byIE.set(k,[]).get(k)).push(j)}}
 const L=(a,b)=>`<div class=li><span>${a}</span><span>${b||'—'}</span></div>`,fi=hasF(i),k=x=>['No','Sí'].includes(x)?x:x||'—',st=(c,lab)=>{const x=v(c,i);return x===''?'—':lab[+x]},sec=(t,b)=>`<section><h4>${t}</h4>${b}</section>`,mats=['piso','pared','techo'].map(m=>L('Material '+m+' (cocina / almacén / comedor)',['co','al','cm'].map(s=>(v(MC[m][s],i)||'—').replace(/^\d+\.\s*/,'')).join(' / ')));
 const hist=byIE.get(C.cod_modular[i]*128+C.anexo[i]).map(j=>`<span class="pill in">${v('periodo_sae',j)} · ${U[j]} usuarios</span>`).join(' ');
 $('#ficha').innerHTML=`<header><button class=x onclick="$('#ficha').hidden=true">✕</button><span class=tag>Ficha de institución educativa</span><h2 style="font-size:1.1rem">${v('nombre_ie',i)}</h2><small>${v('nivel',i)} · Cód. modular ${v('cod_modular',i)} · Anexo ${v('anexo',i)}</small></header>`
 +sec('Ubicación',L('Unidad territorial',v('unidad_territorial',i))+L('Departamento / Provincia',v('departamento',i)+' / '+v('provincia',i))+L('Distrito',v('distrito',i))+L('Área',v('area',i))+L('Cód. local',v('cod_local',i)))
 +sec('Atención SAE · '+v('periodo_sae',i),L('Usuarios',U[i]+(v('rango_usuarios',i)?' · grupo '+v('rango_usuarios',i):''))+L('Comité / Item',v('comite',i)+' / '+v('item',i))+L('Modalidad',v('modalidad',i))+L('Forma de atención',v('forma_atencion',i))+L('Tipo de ración',v('tipo_racion',i))+L('Grupo',v('grupo_sae_educunas',i)))
 +sec('Infraestructura · información 2025',L('Ficha de Infraestructura 2025',fi?'<span class="pill ok">Sí tiene</span>':'<span class="pill no">No tiene</span>')+(fi?L('Kit de menaje',st('kitmenaje',KIT))+L('Kit de cocina',st('kitcocina',KIT))+L('Kit de mobiliario',st('kitmobiliario',KIT))+L('Ambiente de cocina',st('ambientecocina',AMB))+L('Ambiente de almacén',st('ambientealmacen',AMB))+L('Ambiente de comedor',st('ambientecomedor',AMB))+L('Agua',v('abastecimiento_agua_por',i))+L('Servicio higiénico',v('servicio_higienico_conectado_a',i))+L('Alumbrado',v('alumbrado_proviene_de',i))+mats.join('')+L('Cocina óptima',opt(i)?'Sí':'No')+L('Servicios básicos adecuados (agua / desagüe / electricidad)',[v('agua_adecuada',i),v('desague_adecuado',i),v('electricidad_adecuada',i)].map(k).join(' / ')):`<div class=note style="margin-top:8px">Sin Ficha 2025: no hay datos de estado de la infraestructura.</div>`))
 +sec('Presencia por periodo',hist);$('#ficha').hidden=false}
/* ---------- render ---------- */
const filtros=()=>FIL.map(([c])=>Dd[c][sel[c]]?lb(Dd[c][sel[c]]):null).filter(Boolean).join(' · ');
function render(){R=[];const ixx=ix(0);$('#ttl').textContent=TT[tab];$('#out').innerHTML=tab==='his'?T.his():T[tab](ixx);
 $('#meta').innerHTML=`<b>${fmt(ixx.length)}</b> SSEE · <b>${fmt(ixx.reduce((a,i)=>a+U[i],0))}</b> usuarios · ${filtros()||'sin filtros'}`;
 if(tab==='grp')drawMap();if(tab==='fic'){fres();$('#q').oninput=e=>{QS=e.target.value;fres()}}}
$('#filtros').innerHTML=FIL.map(([c,l])=>`<label>${l}<select data-c=${c}>${c==='periodo_sae'?'':'<option value=-1>Todos</option>'}${Dd[c].map((x,k)=>`<option value=${k} ${sel[c]===k?'selected':''}>${lb(x)}</option>`).join('')}</select></label>`).join('')+'<button class=btn style="background:#64748b" id=reset>✕ Limpiar</button>';
$('#filtros').onchange=e=>{sel[e.target.dataset.c]=+e.target.value;render()};
$('#reset').onclick=()=>{FIL.forEach(([c])=>sel[c]=-1);sel.periodo_sae=Dd.periodo_sae.indexOf('2027');document.querySelectorAll('#filtros select').forEach(s=>s.value=sel[s.dataset.c]);render()};
$('#tabs').onclick=e=>{const b=e.target.closest('button');if(!b)return;tab=b.dataset.t;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('on',x===b));render();scrollTo(0,0)};
$('#theme').onclick=()=>{const d=document.documentElement;d.dataset.theme=(d.dataset.theme||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'))==='dark'?'light':'dark'};
$('#out').onclick=e=>{const m=e.target.closest('[data-mat]');if(m){MAT=m.dataset.mat;return render()}const r=e.target.closest('tr[data-k]'),f=e.target.closest('tr[data-f]');
 if(f)return ficha(+f.dataset.f);if(!r)return;const[t,k]=r.dataset.k.split(':');if(t==='ut'){sel.unidad_territorial=+k;document.querySelector('[data-c=unidad_territorial]').value=k;render()}else{G.sel=k;drawMap()}};
$('#out').onchange=e=>{if(e.target.id==='gby'){G.by=e.target.value;render()}if(e.target.id==='ggeo'){G.geo=e.target.value;render()}};
/* ---------- reportes ---------- */
const CSS='body{font-family:Calibri,Arial,sans-serif;color:#0f172a}h1{color:#0b1f47}h2{color:#1d4ed8;border-bottom:2px solid #f59e0b;font-size:13pt}table{border-collapse:collapse}th,td{border:1px solid #94a3b8;padding:3px 7px;font-size:10pt}th{background:#dbe8f7}';
const rep=()=>`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>${CSS}</style></head><body><h1>En un clic · SAE — ${TT[tab]}</h1><p>Filtros: ${filtros()||'ninguno'} · Generado: ${new Date().toLocaleString('es-PE')}</p><p><i>Infraestructura: información de la Ficha de Infraestructura 2025.</i></p>${R.map(d=>`<h2>${d.t}</h2><table><tr>${d.h.map(x=>`<th>${x}</th>`).join('')}</tr>${d.r.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</table>`).join('')}</body></html>`;
const dl=(txt,name,type)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type}));a.download=name;a.click()};
document.querySelector('.hr').onclick=e=>{const x=e.target.dataset.x;if(!x)return;const nm='SAE_'+tab+'_'+(Dd.periodo_sae[sel.periodo_sae]||'');
 if(x==='pdf')print();if(x==='doc')dl('\ufeff'+rep(),nm+'.doc','application/msword');if(x==='xls')dl('\ufeff'+rep(),nm+'.xls','application/vnd.ms-excel');
 if(x==='csv'){const cs=Object.keys(C),q=s=>'"'+String(s).replace(/"/g,'""')+'"',L=['periodo_sae,'+cs.filter(c=>c!=='periodo_sae').concat(['usuarios','latitud','longitud']).join(',')];for(const i of ix(0))L.push(q(v('periodo_sae',i))+','+cs.filter(c=>c!=='periodo_sae').map(c=>q(v(c,i))).concat([U[i],LA[i],LO[i]]).join(','));dl('\ufeff'+L.join('\n'),'SAE_base_filtrada.csv','text/csv')}};
render();
